services:
  - type: web
    name: whatsapp-broadcast-bot
    runtime: node
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: NODE_OPTIONS
        value: --max_old_space_size=4096
    healthCheckPath: /
    disk:
      name: auth_info_baileys
      mountPath: /app/auth_info_baileys
      sizeGB: 1
