services:
  - type: web
    name: whatsapp-bot
    runtime: docker
    branch: main
    buildCommand: docker build -t whatsapp-bot .
    
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: BOT_OWNERS
        value: +917356008536
      
      - key: MAX_CONCURRENT_BROADCASTS
        value: "3"
      
      - key: BROADCAST_DELAY
        value: "2000"
      
      - key: RATE_LIMIT_WINDOW
        value: "300000"

    disk:
      name: whatsapp-bot-auth
      mountPath: /app/auth_info_baileys
      sizeGB: 1
